# CODE generated by Microsoft CoPilot

CREATE TABLE snapshots (
    id INT AUTO_INCREMENT PRIMARY KEY,
    collection VARCHAR(100) NOT NULL,
    filename VARCHAR(1000) NOT NULL,
    dir VARCHAR(1000) NOT NULL,
    bnum VARCHAR(50),
    md5 VARCHAR(32) NOT NULL,
    `desc` TEXT,
    width INT,
    height INT,
    license VARCHAR(100),
    attribution VARCHAR(100),
    medurl TEXT,
    largeurl TEXT,
    meddirlink TEXT,
    bigdirlink TEXT,
    sourceurl TEXT,
    arttype VARCHAR(100),
    `date` DATETIME,
    ftype VARCHAR(50)
);

CREATE INDEX idx_collection ON snapshots (collection);
CREATE INDEX idx_license ON snapshots (license);
CREATE INDEX idx_attribution ON snapshots (attribution);
CREATE INDEX idx_md5 ON snapshots (md5);
CREATE INDEX idx_arttype ON snapshots (arttype);
CREATE INDEX idx_ftype ON snapshots (ftype);

