#!/bin/bash
#
# Routines to create the Index, Links and Sources file for the Virtual Bible Snapshot Project
# by Pastor Daniel McFeeters
# Licensed under CC0

source "$(dirname "$0")/parsename_functions.sh"

# Define a function to process files in a directory
process_directory() {
    local directory="$1"
    echo -n "Processing files in directory: $directory ..."
    local linkfile="$directory/0000 Index, Links and Sources.md"
    if [[ -e "$linkfile" ]]; then
        hash=`ls -l --hide 0000\ Index\,\ Links\ and\ Sources.md "$directory" | sha1sum`
        checkhash=`tail -1 "$linkfile"`
	if [[ "$hash" == "$checkhash" ]]; then
		echo " already up-to-date, skipping."
		return 1	
	fi
    fi
    
    touch "$linkfile"
    echo "## Directory Index, Links, and Sources ##" > "$linkfile"
    echo "*This file is automatically generated. Edits will be overwritten.*" >> "$linkfile"
    echo "" >> "$linkfile"
    echo "For more information and terms visit [snapshots.vrbm.org](https://snapshots.vrbm.org/)" >> "$linkfile"
    echo "" >> "$linkfile"
    
    # Use a 'for' loop to iterate through the files in the current directory
    for file in "$directory"/*; do
	if [[ -d "$file" ]]; then
		continue;
	fi
	basefile=`basename "$file"`
        if [[ "$basefile" = "0000 Index, Links and Sources.md" ]]; then
		continue;
	fi
	link=`get_sourcelink "$file"`
        # Use a regular expression to extract the desired part of the filename
        if [[ "$file" =~ ([^/]+)\.([^\.]+)$ ]]; then
            filename="${BASH_REMATCH[1]}"
            extension="${BASH_REMATCH[2]}"
	    if [[ "$link" != "" ]]; then
	        echo "* [$filename.$extension" >> "$linkfile"
	        echo "      ]($link)" >> "$linkfile"
	    else
	    	echo "* $filename.$extension" >> "$linkfile"
	    fi
	    # Try EXIF first
		image_description=$(exiftool -s -s -s -ImageDescription "$file")

		# If EXIF empty, try XMP dc:Description
		if [ -z "$image_description" ]; then
		    image_description=$(exiftool -s -s -s -XMP-dc:Description "$file")
		fi

		# Output if non-empty
		if [ -n "$image_description" ]; then
		    echo "    * $image_description" >> "$linkfile"
		fi


        fi
    done
    hash=`ls -l --hide 0000\ Index\,\ Links\ and\ Sources.md "$directory" | sha1sum`
    echo "" >> "$linkfile"
    echo "$hash" >> "$linkfile"
    echo ""
}

export -f process_directory  # Export the function so it's available to subshells
export -f get_sourcelink

# Use the 'find' command to locate directories and execute the function
find -type d -exec bash -c 'process_directory "$0"' {} \;
find -name "0000 Index, Links and Sources.md" -type f -size 243c -delete
date > VERSION.md
